apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "healthsphere.fullname" . }}-backend
  labels:
    app: {{ include "healthsphere.name" . }}-backend
spec:
{{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "healthsphere.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "healthsphere.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP

          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "healthsphere.fullname" . }}-config
                  key: ENVIRONMENT

          resources:
{{ toYaml .Values.backend.resources | indent 12 }}

