---
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker.io
    state: present

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add ansible user to docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: true
